server:
  port: 8082

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodr_db
    username: foodr_user
    password: foodr_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.foodr.restaurant: DEBUG
